### ISSUE TITLE
.PAL Palette file support

### ISSUE THREAD

**Issue by Ukysseus** [bartlomiejduda/ImageHeat#1]
Hi, is support for .PAL palette files planned? To have the correct colors with some PS1 .BIN sprites

**Comment by bartlomiejduda** [comment]
Hi. Yes, support for PAL files is planned. Also support for palletes embedded in image files is planned. That includes PAL4 and PAL8 pixel formats.

I'll leave this issue open for now and I will close it when new program's version with the PAL support will be released.

**Comment by bartlomiejduda** [comment]
PAL files support added in version **v0.6.3**
I'm closing this issue.
